# .github/workflows/deploy.yml
name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  APP_ID:  ${{ secrets.GCP_APP_NAME }}
  RUN_REGION: us-central1
  SA_KEY_JSON: ${{ secrets.GCP_CREDENTIALS }}
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true
          
      - name: Create json
        id: create-json
        uses: jsdaniell/create-json@1.2.2
        with:
          name: "firebase_credentials.json"
          json: ${{ secrets.FIREBASE_CREDENTIALS }}
      - name: Commit json
        run: git config --global user.email "gallichan.bryce@gmail.com" && git config --global user.name "gallichan.bryce" && git add . && git add --force firebase_credentials.json && git status && git commit -a -m "Deploy Cloud Run Commit"
      # Build and push image to Google Container Registry
      - name: Build
        run: |
          gcloud config set project $PROJECT_ID
          gcloud builds submit --tag gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --project=$PROJECT_ID

      - name: Deploy
        run: gcloud run deploy $APP_ID --image gcr.io/$PROJECT_ID/$APP_ID:$GITHUB_SHA --platform managed --region $RUN_REGION --allow-unauthenticated
